<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WIFI-Form</name>
   <tag></tag>
   <elementGuidId>dc6c371e-0e1a-4469-b5b5-15c8c227fb42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wifi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wifi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; WIFI-Form&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0db3f060-c22a-4702-ad7f-95d046a66ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../notification_2021/wifi_form.pdf</value>
      <webElementGuid>cc44c810-bf90-4aa7-9b46-b953033eb51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_new</value>
      <webElementGuid>f4e123c9-16c4-4f45-9106-3f44b9013f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wifi</value>
      <webElementGuid>94007105-83ea-46f9-8a48-d979f49ccaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
            WIFI-Form</value>
      <webElementGuid>7daa4db0-bb0b-474c-bcca-f06aa6dfde3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wifi&quot;)</value>
      <webElementGuid>85121235-6d4b-4cc4-92bc-4ebcdc4a03fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wifi']</value>
      <webElementGuid>1d77bd52-05cc-447b-85fc-ec1f19e03fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mySidenav']/a[5]</value>
      <webElementGuid>6c134051-0204-423e-9d33-e3a44a645a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APP'])[1]/following::a[1]</value>
      <webElementGuid>5d51a4c1-3cb3-4323-afd9-dca5a164a00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[3]</value>
      <webElementGuid>fcce65f9-e757-4eb0-889a-6b6fea7448ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WIFI-Form']/parent::*</value>
      <webElementGuid>df5bf2af-1ce5-4c0b-a03f-6328aba0f45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../notification_2021/wifi_form.pdf')]</value>
      <webElementGuid>c4e80374-c7c7-4757-998e-a5e040cee6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>30622b17-9883-4b8c-941f-09e5d6fdc568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../notification_2021/wifi_form.pdf' and @id = 'wifi' and (text() = '
        
            WIFI-Form' or . = '
        
            WIFI-Form')]</value>
      <webElementGuid>563b2575-124c-440d-b801-95a3c2659066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
