<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Library</name>
   <tag></tag>
   <elementGuidId>6252e80a-24ea-446a-abe2-e09020dd2f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div/div/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Library&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>214a60ac-8a29-4634-9232-3e7ce2c06264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://aulib.annamalaiuniversity.ac.in/</value>
      <webElementGuid>c31e77b7-e5e4-4863-9e2a-da975d7152bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Library</value>
      <webElementGuid>b972eaab-91fe-477b-9470-dec0cfe479bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>34855b7c-ecf3-4943-aab6-3e422d2c4263</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>94721ddb-1b4b-4d5d-a3cc-28b65c579326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Library')])[2]</value>
      <webElementGuid>dc6010a1-9d7a-47d7-82c4-57cbf6d732a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infrastructure'])[3]/following::a[1]</value>
      <webElementGuid>0ec28899-404f-4ffc-913e-9b07202d15af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::a[2]</value>
      <webElementGuid>6e5a20ef-8728-4cfc-80cd-3879af62a3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laboratory C.I.S.L'])[1]/preceding::a[1]</value>
      <webElementGuid>9cad407f-6211-44fc-8e28-7284738cd76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports Centre'])[1]/preceding::a[2]</value>
      <webElementGuid>1468bcb0-d6a1-4d1c-a603-b8d6e6340b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://aulib.annamalaiuniversity.ac.in/'])[2]</value>
      <webElementGuid>70d36c18-1297-47d7-84d1-7b149566ce81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>00d2809b-696b-42ca-bc61-26939526f595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://aulib.annamalaiuniversity.ac.in/' and (text() = 'Library' or . = 'Library')]</value>
      <webElementGuid>5b9aaebb-b850-46fa-b9ee-d8ba4ce51660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
